workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == "master" && $CI_COMMIT_TITLE != $DOCS_AUTOCOMMIT_TITLE
    - if: $CI_COMMIT_BRANCH =~ /^\d\.\d\.\d$/ && $CI_COMMIT_TITLE != $DOCS_AUTOCOMMIT_TITLE
    - if: $TEST || $WHAT

# to skip ci add [ci skip] or [skip ci] in commit message in any capitalization

stages:
  - mirroring
  - build
  - publish

job_mirror:
  stage: mirroring
  rules:
    - if: $TEST==null && $CI_COMMIT_BRANCH == "master"
  tags:
    - dev-host
  dependencies: []
  script:
    - ~/gitsync_columnar.sh
  cache: {}

osx:
  stage: build
  interruptible: true
  retry: 1
  variables:
    CACHEB: "cache"
  tags:
    - mac
    - build
  script:
    - cmake -DBUILD_TAG=$RELEASE_TAG -DDISTR=macos -DPACK_COLUMNAR=1 .
    - make -j2 package
  artifacts:
    paths:
      - manticore-*.tar.gz
    when: on_success
    expire_in: 12 hrs
  cache:
    key: mojave_columnar
    paths:
      - cache/fastpfor*64

windows:
  stage: build
  interruptible: true
  tags:
    - windev19
    - build
  variables:
    CACHEB: "x:/cache"
  script:
    - 'net use x: \\\\VBOXSRV\\shared'
    - cmake -DPACK=1 -DBUILD_TAG=$RELEASE_TAG -DDISTR=default -DPACK_COLUMNAR=1 .
    - cmake --build . --target package
  artifacts:
    paths:
      - manticore-*.zip
    when: on_success
    expire_in: 12 hrs

.redhat_based:
  stage: build
  interruptible: true
  tags:
    - docker
  variables:
    CACHEB: "cache"
  script:
    - ln -s $(pwd) /manticore012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789/src
    - cd /manticore012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789/src
    - cmake -DPACK=1 -DBUILD_TAG=$RELEASE_TAG -DPACK_COLUMNAR=1 .
    - make -j4 package
  artifacts:
    paths:
      - manticore*.rpm
    when: on_success
    expire_in: 12 hrs
  cache:
    paths:
      - cache/fastpfor*64

.debian_based:
  stage: build
  interruptible: true
  tags:
    - docker
  variables:
    CACHEB: "cache"
  script:
    - cmake -DPACK=1 -DBUILD_TAG=$RELEASE_TAG -DPACK_COLUMNAR=1 .
    - make -j4 package
  artifacts:
    paths:
      - manticore*deb
    when: on_success
    expire_in: 12 hrs
  cache:
    paths:
      - cache/fastpfor*64

rhel7:
  extends:
    - .redhat_based
  image: registry.gitlab.com/manticoresearch/dev/centos7_cmake:317
  cache:
    key: rhel7_columnar

rhel8:
  extends:
    - .redhat_based
  image: registry.gitlab.com/manticoresearch/dev/centos8_cmake:317
  cache:
    key: rhel8_columnar

stretch:
  extends:
    - .debian_based
  image: registry.gitlab.com/manticoresearch/dev/stretch_cmake:317
  cache:
    key: stretch_columnar

xenial:
  extends:
    - .debian_based
  image: registry.gitlab.com/manticoresearch/dev/xenial_cmake:317
  cache:
    key: xenial_columnar

bionic:
  extends:
    - .debian_based
  image: registry.gitlab.com/manticoresearch/dev/bionic_cmake:317
  cache:
    key: bionic_columnar

focal:
  extends:
    - .debian_based
  image: registry.gitlab.com/manticoresearch/dev/focal_cmake:317
  cache:
    key: focal_columnar

buster:
  extends:
    - .debian_based
  image: registry.gitlab.com/manticoresearch/dev/buster_cmake:317
  cache:
    key: buster_columnar

collect_repo:
  stage: publish
  interruptible: true
  tags:
    - dev-host
  script:
    - echo "Collected packages"
    - ls -1
    - ~/upload_repo.sh
  dependencies: [rhel7, rhel8, stretch, xenial, bionic, buster, focal, osx, windows]
  cache: {}
