# global settings will be applied to all jobs
variables:
  CMAKE_INTERPROCEDURAL_OPTIMIZATION: 0

stages:
  - build
  - repoupload

workflow:
  rules:
    - when: always

.redhat_based:
  stage: build
  interruptible: true
  tags:
    - docker
  variables:
    CACHEB: "cache"
  script:
    - ln -s $(pwd) /manticore012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789/src
    - cd /manticore012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789/src
    - mkdir build && cd build
    - cmake -GNinja -DPACK=1 ..
    - cmake --build . --target package
  artifacts:
    paths:
      - build/manticore*.rpm
    when: on_success
    expire_in: 12 hrs
  cache:
    paths:
      - cache

.debian_based:
  stage: build
  interruptible: true
  tags:
    - docker
  variables:
    CACHEB: "cache"
  script:
    - mkdir build && cd build
    - cmake -GNinja -DPACK=1 ..
    - cmake --build . --target package
  artifacts:
    paths:
      - build/manticore*deb
    when: on_success
    expire_in: 12 hrs
  cache:
    paths:
      - cache

.collect_job:
  variables:
    GIT_STRATEGY: fetch
  stage: repoupload
  interruptible: true
  cache: { }
  tags:
    - dev-host


osx:
  stage: build
  interruptible: true
  retry: 1
  variables:
    CACHEB: "cache"
  tags:
    - mac
    - build
  script:
    - mkdir build && cd build
    - cmake -GNinja -DDISTR_BUILD=macos ..
    - cmake --build . --target package
  artifacts:
    paths:
      - build/manticore-*.tar.gz
    when: on_success
    expire_in: 12 hrs
  cache:
    key: mojave_columnar
    paths:
      - cache

collect_osx:
  extends: [ .collect_job ]
  needs: [ osx ]
  script: [ /bin/bash dist/upload_repo_arc.sh ]

windows:
  stage: build
  interruptible: true
  tags:
    - windev19
    - build
  variables:
    CACHEB: "x:/cache"
  script:
    - 'net use x: \\\\VBOXSRV\\shared'
    - mkdir build
    - cd build
    - cmake -DDISTR_BUILD=windows ..
    - cmake --build . --target package --config RelWithDebInfo
  artifacts:
    paths:
      - build/manticore-*.zip
    when: on_success
    expire_in: 12 hrs

collect_windows:
  extends: [ .collect_job ]
  needs: [ windows ]
  script: [ /bin/bash dist/upload_repo_arc.sh ]


rhel7:
  extends: [ .redhat_based ]
  image: registry.gitlab.com/manticoresearch/dev/centos7_clang:7
  cache:
    key: rhel7_columnar

collect_rhel7:
  extends: [ .collect_job ]
  script: [ /bin/bash dist/upload_repo_rpm.sh ]
  variables:
    DISTRO: 7
  needs: [ rhel7 ]


rhel8:
  extends: [ .redhat_based ]
  image: registry.gitlab.com/manticoresearch/dev/centos8_clang:11
  cache:
    key: rhel8_columnar

collect_rhel8:
  extends: [ .collect_job ]
  script: [ /bin/bash dist/upload_repo_rpm.sh ]
  variables:
    DISTRO: 8
  needs: [ rhel8 ]


stretch:
  extends: [ .debian_based ]
  image: registry.gitlab.com/manticoresearch/dev/stretch_clang:13
  cache:
    key: stretch_columnar
  variables:
    SKIP_SECONDARY: "1"    

collect_stretch:
  extends: [ .collect_job ]
  script: [ /bin/bash dist/upload_repo_deb.sh ]
  variables:
    DISTRO: stretch
  needs: [ stretch ]


xenial:
  extends: [ .debian_based ]
  image: registry.gitlab.com/manticoresearch/dev/xenial_clang:12
  cache:
    key: xenial_columnar
  variables:
    SKIP_SECONDARY: "1"    

collect_xenial:
  extends: [ .collect_job ]
  script: [ /bin/bash dist/upload_repo_deb.sh ]
  variables:
    DISTRO: xenial
  needs: [ xenial ]


bionic:
  extends: [ .debian_based ]
  image: registry.gitlab.com/manticoresearch/dev/bionic_clang:13
  cache:
    key: bionic_columnar

collect_bionic:
  extends: [ .collect_job ]
  script: [ /bin/bash dist/upload_repo_deb.sh ]
  variables:
    DISTRO: bionic
  needs: [ bionic ]


focal:
  extends: [ .debian_based ]
  image: registry.gitlab.com/manticoresearch/dev/focal_clang:13
  cache:
    key: focal_columnar

collect_focal:
  extends: [ .collect_job ]
  script: [ /bin/bash dist/upload_repo_deb.sh ]
  variables:
    DISTRO: focal
  needs: [ focal ]

jammy:
  extends: [ .debian_based ]
  image: registry.gitlab.com/manticoresearch/dev/jammy_cmake:323
  cache:
    key: jammy_columnar

collect_jammy:
  extends: [ .collect_job ]
  script: [ /bin/bash dist/upload_repo_deb.sh ]
  variables:
    DISTRO: jammy
  needs: [ jammy ]

buster:
  extends: [ .debian_based ]
  image: registry.gitlab.com/manticoresearch/dev/buster_clang:13
  cache:
    key: buster_columnar

collect_buster:
  extends: [ .collect_job ]
  script: [ /bin/bash dist/upload_repo_deb.sh ]
  variables:
    DISTRO: buster
  needs: [ buster ]

bullseye:
  extends: [ .debian_based ]
  image: registry.gitlab.com/manticoresearch/dev/bullseye_clang:13
  cache:
    key: bullseye_columnar

collect_bullseye:
  extends: [ .collect_job ]
  script: [ /bin/bash dist/upload_repo_deb.sh ]
  variables:
    DISTRO: bullseye
  needs: [ bullseye ]
